### ISSUE TITLE
Carregador de missions prefabricades a traves de fitxer extern

### ISSUE THREAD

**Issue by Legolasindar** [CavallersDelCel/1RA_Combat_Dinamic#2]
Crear una opció al pal de la bandera perque es pugui carregar una missió prefabricada anteriorment a traves d'un fitxer extern. Similar a la creació del camp base.
Seria bo tenir l'opció al pal de la bandera, que obri una finestra i que es mostri un petit llistat amb els fitxers a carregar a una carpeta concreta.
La carpeta podria ser _/arma3/MPMissions/1ra_cd_missions_ o _/arma3/1ra_cd_missions_ per exemple.

**Comment by TheMagnetar** [comment]
En la meva opinió ha de ser algo que poguem sincronitzar amb Arma3sync.

**Comment by Legolasindar** [comment]
Doncs llavors hauria de ser millor una carpeta aliena a MPMissions, es a dir _/arma3/1ra_cd_missions_ per exemple.

**Comment by TheMagnetar** [comment]
Ja no és possible degut a la 1.54.
